import type {
  ActivityCategory,
  MedicalSection,
  PhraseCategory,
  QuickWordsConfig,
} from '../types/customization';

export const CARE_CONTENT_ARCHITECTURE_VERSION = 4;

export const CARE_PHRASE_CATEGORIES: PhraseCategory[] = [
  {
    id: 'communication',
    name: 'Communication',
    phrases: [
      { en: 'Yes', hi: 'हां' },
      { en: 'No', hi: 'नहीं' },
      { en: 'Wait a moment', hi: 'एक पल रुको' },
      { en: 'Let me think', hi: 'मुझे सोचने दो' },
      { en: "I don't understand", hi: 'समझ नहीं आया' },
      { en: 'Repeat that', hi: 'दोहराएं' },
      { en: 'Ask yes or no', hi: 'हां या नहीं पूछो' },
      { en: 'Speak slowly', hi: 'धीरे बोलो' },
      { en: 'Thank you', hi: 'धन्यवाद' },
      { en: 'Sorry', hi: 'माफ़ी' },
    ],
  },
  {
    id: 'feelings',
    name: 'Feelings & Emotions',
    phrases: [
      { en: 'I am okay', hi: 'मैं ठीक हूं' },
      { en: 'I am scared', hi: 'मुझे डर लग रहा है' },
      { en: 'I am anxious', hi: 'मुझे चिंता है' },
      { en: 'I feel uncomfortable', hi: 'मुझे असहज लग रहा है' },
      { en: 'I am tired', hi: 'मैं थक गया हूं' },
      { en: 'I feel lonely', hi: 'मुझे अकेलापन लग रहा है' },
      { en: 'I am grateful', hi: 'मैं आभारी हूं' },
      { en: 'I love you', hi: 'मैं तुमसे प्यार करता हूं' },
      { en: 'I miss you', hi: 'मैं तुम्हें याद करता हूं' },
      { en: 'Pray for me', hi: 'मेरे लिए प्रार्थना करो' },
    ],
  },
  {
    id: 'people',
    name: 'People & Visitors',
    phrases: [
      { en: 'Call family', hi: 'परिवार को बुलाओ' },
      { en: 'Call nurse', hi: 'नर्स को बुलाओ' },
      { en: 'Call doctor', hi: 'डॉक्टर को बुलाओ' },
      { en: 'Call caretaker', hi: 'केयरटेकर को बुलाओ' },
      { en: 'Who is there?', hi: 'वहां कौन है?' },
      { en: 'Who is at the door?', hi: 'दरवाज़े पर कौन है?' },
      { en: 'I want to video call', hi: 'मैं वीडियो कॉल करना चाहता हूं' },
      { en: "I don't want visitors", hi: 'मुझे कोई नहीं चाहिए' },
      { en: 'Ask them to wait', hi: 'उन्हें रुकने को कहो' },
    ],
  },
];

export const CARE_MEDICAL_SECTIONS: MedicalSection[] = [
  {
    id: 'airway',
    title: 'AIRWAY & VITALS',
    titleHi: 'वायुमार्ग / वाइटल्स',
    items: [
      { en: 'TT Suction needed now', hi: 'TT सक्शन अभी चाहिए', urgent: true },
      { en: 'Oral suction needed', hi: 'ओरल सक्शन चाहिए', urgent: true },
      { en: 'Breathing problem - Ambu bag', hi: 'सांस की तकलीफ', urgent: true },
      { en: 'Breathing discomfort', hi: 'सांस में तकलीफ', urgent: true },
      { en: 'Check vitals - O2, Pulse', hi: 'वाइटल्स चेक करो', urgent: true },
      { en: 'Ventilator alarm - check', hi: 'वेंटिलेटर अलार्म', urgent: true },
      { en: 'Check TT cuff / balloon pressure', hi: 'टीटी कफ / बैलून प्रेशर चेक करें', urgent: true },
      { en: 'Call nurse immediately', hi: 'नर्स को तुरंत बुलाओ', urgent: true },
    ],
  },
  {
    id: 'bed',
    title: 'BED & POSITION',
    titleHi: 'बिस्तर / करवट',
    items: [
      { en: 'Turn to Left Side', hi: 'बाईं करवट' },
      { en: 'Turn to Right Side', hi: 'दाईं करवट' },
      { en: 'Raise my head', hi: 'सिर ऊपर करो' },
      { en: 'Lower my head', hi: 'सिर नीचे करो' },
      { en: 'Fix Pillow', hi: 'तकिया ठीक करो' },
      { en: 'Adjust Head / Neck', hi: 'सर ठीक करो' },
      { en: 'Adjust Hands & Legs', hi: 'हाथ-पैर ठीक करो' },
      { en: 'Back care needed', hi: 'बैक केयर' },
    ],
  },
  {
    id: 'daily',
    title: 'DAILY CARE',
    titleHi: 'रोज़ देखभाल',
    items: [
      { en: 'I need Water', hi: 'पानी चाहिए' },
      { en: 'Oral Care / Clean Teeth', hi: 'मुंह / दांत साफ करो' },
      { en: 'Clean Face / Eyes', hi: 'चेहरा / आंखें साफ करो' },
      { en: 'Eye Drops', hi: 'आई ड्रॉप्स' },
      { en: 'Toilet / Urine Pot', hi: 'टॉयलेट / पॉट' },
      { en: 'Fan', hi: 'पंखा' },
      { en: 'Blanket / Shawl', hi: 'कंबल / शॉल' },
      { en: 'AC', hi: 'AC' },
    ],
  },
  {
    id: 'symptoms',
    title: 'SYMPTOMS',
    titleHi: 'लक्षण / तकलीफ',
    items: [
      { en: 'I am in severe pain', hi: 'बहुत दर्द हो रहा है', urgent: true },
      { en: 'Chest discomfort', hi: 'छाती में तकलीफ', urgent: true },
      { en: 'Fever', hi: 'बुखार' },
      { en: 'Feeling cold / shivering', hi: 'ठंड / कंपकंपी' },
      { en: 'Feeling hot / sweating', hi: 'गर्मी / पसीना' },
      { en: 'Panic / Anxiety', hi: 'घबराहट हो रही है' },
      { en: 'Itching', hi: 'खुजली हो रही है' },
      { en: 'Too tired / need rest', hi: 'बहुत थकान / आराम चाहिए' },
    ],
  },
];

export const CARE_QUICK_WORDS: QuickWordsConfig = {
  enabled: true,
  highColor: 'muted_maroon',
  mediumColor: 'warm_teal',
  coreWords: [
    { en: 'Yes', hi: 'हां', enabled: true },
    { en: 'No', hi: 'नहीं', enabled: true },
    { en: 'Wait', hi: 'रुको', enabled: true },
    { en: 'Stop', hi: 'रुको', enabled: true },
    { en: 'Help', hi: 'मदद', enabled: true },
    { en: 'Pain', hi: 'दर्द', enabled: true },
  ],
  categories: [
    {
      id: 'emergency',
      heading: 'Medical / Urgent',
      headingHi: 'मेडिकल / अर्जेंट',
      color: '#A64E3F',
      words: [
        {
          id: 'medical_tt_suction',
          en: 'TT Suction',
          hi: 'टीटी सक्शन',
          enabled: true,
          priority: 'high',
          relatedWordIds: ['medical_oral_suction', 'medical_breathing_ambu', 'medical_bp_pulse'],
          phrases: [
            { en: 'Do TT suction', hi: 'टीटी सक्शन करें' },
            { en: 'Remove secretions from suction side', hi: 'स्राव साफ करें' },
            { en: 'Check the trach tube', hi: 'ट्रैक ट्यूब चेक करें' },
            { en: 'I am feeling some obstruction', hi: 'मुझे कुछ रुकावट लग रही है' },
          ],
        },
        {
          id: 'medical_oral_suction',
          en: 'Oral Suction',
          hi: 'ओरल सक्शन',
          enabled: true,
          priority: 'high',
          relatedWordIds: ['medical_tt_suction', 'medical_breathing_ambu', 'medical_bp_pulse'],
          phrases: [
            { en: 'Do oral suction', hi: 'ओरल सक्शन करें' },
            { en: 'There is saliva in my mouth', hi: 'मेरे मुंह में लार है' },
            { en: 'Do oral care and clean my teeth', hi: 'ओरल केयर करें और मेरे दांत साफ करें' },
            { en: 'I am choking on secretions', hi: 'मुझे स्राव से घुटन हो रही है' },
            { en: 'Come quickly', hi: 'जल्दी आइए' },
          ],
        },
        {
          id: 'medical_breathing_ambu',
          en: 'Breathing / Ambu',
          hi: 'सांस / एम्बू',
          enabled: true,
          priority: 'high',
          relatedWordIds: ['medical_bp_pulse', 'medical_chest_nebulization', 'medical_severe_pain'],
          phrases: [
            { en: 'I am having trouble breathing', hi: 'मुझे सांस लेने में तकलीफ हो रही है' },
            { en: 'Use the Ambu bag', hi: 'एम्बू बैग का उपयोग करें' },
            { en: 'Check oxygen support', hi: 'ऑक्सीजन सपोर्ट चेक करें' },
            { en: 'Check TT cuff pressure', hi: 'टीटी कफ प्रेशर चेक करें' },
            { en: 'Call nurse now', hi: 'नर्स को अभी बुलाइए' },
          ],
        },
        {
          id: 'medical_bp_pulse',
          en: 'BP / Pulse',
          hi: 'बीपी / पल्स',
          enabled: true,
          priority: 'high',
          relatedWordIds: ['medical_breathing_ambu', 'medical_chest_nebulization', 'medical_severe_pain'],
          phrases: [
            { en: 'Check my BP', hi: 'मेरा बीपी चेक करें' },
            { en: 'Check my pulse', hi: 'मेरी पल्स चेक करें' },
            { en: 'I feel dizzy', hi: 'मुझे चक्कर आ रहे हैं' },
            { en: 'I feel weak', hi: 'मुझे कमजोरी लग रही है' },
            { en: 'Check the monitor', hi: 'मॉनिटर चेक करें' },
          ],
        },
        {
          id: 'medical_chest_nebulization',
          en: 'Chest / Nebulization',
          hi: 'छाती / नेबुलाइजेशन',
          enabled: true,
          priority: 'high',
          relatedWordIds: ['medical_breathing_ambu', 'medical_bp_pulse', 'medical_severe_pain'],
          phrases: [
            { en: 'I have chest discomfort', hi: 'मेरी छाती में तकलीफ है' },
            { en: 'My chest feels tight / chest congestion', hi: 'मेरी छाती भारी लग रही है / छाती में जकड़न' },
            { en: 'Give nebulization', hi: 'नेबुलाइजेशन दें' },
          ],
        },
        {
          id: 'medical_severe_pain',
          en: 'Severe Pain',
          hi: 'तेज दर्द',
          enabled: true,
          priority: 'high',
          relatedWordIds: ['medical_bp_pulse', 'medical_chest_nebulization'],
          phrases: [
            { en: 'Back pain / headache', hi: 'पीठ दर्द / सिर दर्द' },
            { en: 'Throat pain', hi: 'गले में दर्द' },
            { en: 'Pain in hands and legs', hi: 'हाथ-पैर में दर्द' },
            { en: 'Stomach pain', hi: 'पेट दर्द' },
          ],
        },
      ],
    },
    {
      id: 'position',
      heading: 'Position',
      headingHi: 'पोजीशन',
      color: '#C69A45',
      words: [
        {
          id: 'position_turn_left',
          en: 'Turn Left / Left Karvat',
          hi: '',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['position_turn_right', 'position_head_up', 'position_fix_pillow'],
        },
        {
          id: 'position_turn_right',
          en: 'Turn Right / Right Karvat',
          hi: '',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['position_turn_left', 'position_head_up', 'position_fix_pillow'],
        },
        {
          id: 'position_head_up',
          en: 'Head Up',
          hi: 'सिर ऊपर',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['position_head_down', 'position_fix_pillow', 'position_adjust_limbs'],
          phrases: [
            { en: 'Raise bed angle', hi: 'बेड एंगल ऊपर करें' },
            { en: 'Raise the backrest', hi: 'बैकरेस्ट ऊपर करें' },
            { en: 'Shift me up', hi: 'मुझे ऊपर खिसकाएं' },
            { en: 'Adjust bed angle to sitting position', hi: 'बेड एंगल बैठने की स्थिति में करें' },
          ],
        },
        {
          id: 'position_head_down',
          en: 'Head Down',
          hi: 'सिर नीचे',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['position_head_up', 'position_fix_pillow', 'position_adjust_limbs'],
          phrases: [
            { en: 'Lower bed angle', hi: 'बेड एंगल नीचे करें' },
            { en: 'Lower the backrest', hi: 'बैकरेस्ट नीचे करें' },
            { en: 'Shift me up', hi: 'मुझे ऊपर खिसकाएं' },
            { en: 'Adjust bed angle to sitting position', hi: 'बेड एंगल बैठने की स्थिति में करें' },
          ],
        },
        {
          id: 'position_fix_pillow',
          en: 'Fix Pillow',
          hi: 'तकिया ठीक करें',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['position_head_up', 'position_head_down', 'position_adjust_limbs'],
          phrases: [
            { en: 'Fix my pillow', hi: 'मेरा तकिया ठीक करें' },
            { en: 'Move the pillow higher', hi: 'तकिया थोड़ा ऊपर करें' },
            { en: 'Move the pillow lower', hi: 'तकिया थोड़ा नीचे करें' },
            { en: 'Support my neck better', hi: 'मेरी गर्दन को बेहतर सहारा दें' },
            { en: 'That is better', hi: 'अब बेहतर है' },
          ],
        },
        {
          id: 'position_adjust_limbs',
          en: 'Adjust Hands & Legs',
          hi: 'हाथ और पैर ठीक करें',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['position_fix_pillow', 'position_turn_left', 'position_turn_right'],
          phrases: [
            { en: 'Adjust my hands', hi: 'मेरे हाथ ठीक करें' },
            { en: 'Adjust my legs', hi: 'मेरे पैर ठीक करें' },
            { en: 'My arm is uncomfortable', hi: 'मेरा हाथ असुविधाजनक है' },
            { en: 'My leg needs support', hi: 'मेरे पैर को सहारा चाहिए' },
            { en: 'That is better now', hi: 'अब बेहतर है' },
          ],
        },
      ],
    },
    {
      id: 'daily',
      heading: 'Daily Care',
      headingHi: 'डेली केयर',
      color: '#8FAE72',
      words: [
        {
          id: 'daily_water',
          en: 'Water',
          hi: 'पानी',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['daily_eyes_face', 'daily_fan_ac', 'daily_ac'],
        },
        {
          id: 'daily_eyes_face',
          en: 'Eyes / Face',
          hi: 'आंखें / चेहरा',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['daily_water', 'daily_blanket', 'daily_ac'],
          phrases: [
            { en: 'Put eye drops', hi: 'आई ड्रॉप्स डालें' },
            { en: 'My eyes are dry', hi: 'मेरी आंखें सूखी हैं' },
            { en: 'Clean my eyes', hi: 'मेरी आंखें साफ करें' },
            { en: 'Clean my face', hi: 'मेरा चेहरा साफ करें' },
            { en: 'My eyes are irritated', hi: 'मेरी आंखों में जलन है' },
          ],
        },
        {
          id: 'daily_blanket',
          en: 'Blanket',
          hi: 'कंबल',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['daily_fan_ac', 'daily_eyes_face', 'daily_ac'],
          phrases: [
            { en: 'Cover me', hi: 'मुझे कवर करें' },
            { en: 'I feel cold', hi: 'मुझे ठंड लग रही है' },
            { en: 'Use a light blanket', hi: 'हल्का कंबल दीजिए' },
            { en: 'Remove the blanket', hi: 'कंबल हटा दें' },
            { en: 'Adjust the blanket', hi: 'कंबल ठीक करें' },
          ],
        },
        {
          id: 'daily_fan_ac',
          en: 'Fan',
          hi: 'पंखा',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['daily_ac', 'daily_blanket', 'daily_water'],
          phrases: [
            { en: 'Turn the fan on', hi: 'पंखा चालू करें' },
            { en: 'Turn the fan off', hi: 'पंखा बंद करें' },
            { en: 'Increase the fan', hi: 'पंखा तेज करें' },
            { en: 'Reduce the fan', hi: 'पंखा धीमा करें' },
          ],
        },
        {
          id: 'daily_toilet',
          en: 'Urine Pot / Toilet',
          hi: 'यूरिन पॉट / टॉयलेट',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['daily_ac', 'daily_water', 'daily_blanket'],
          phrases: [
            { en: 'I need the urine pot now', hi: 'मुझे अभी यूरिन पॉट चाहिए' },
            { en: 'Remove the urine pot', hi: 'यूरिन पॉट हटा दें' },
          ],
        },
        {
          id: 'daily_ac',
          en: 'AC',
          hi: 'एसी',
          enabled: true,
          priority: 'medium',
          relatedWordIds: ['daily_fan_ac', 'daily_blanket', 'daily_water'],
          phrases: [
            { en: 'Turn on the AC', hi: 'एसी चालू करें' },
            { en: 'Turn off the AC', hi: 'एसी बंद करें' },
            { en: 'Increase AC cooling', hi: 'एसी कूलिंग बढ़ाएं' },
            { en: 'Reduce AC cooling', hi: 'एसी कूलिंग कम करें' },
          ],
        },
      ],
    },
  ],
};

export const CARE_ACTIVITY_CATEGORIES: ActivityCategory[] = [
  {
    id: 'tv',
    name: 'TV Channels',
    items: [
      { label: 'Switch ON TV', num: 'ON', speak: 'Switch on TV' },
      { label: 'Switch OFF TV', num: 'OFF', speak: 'Switch off TV' },
      { label: 'News - 508', num: '508', speak: 'Change to channel 508' },
      { label: 'News - 511', num: '511', speak: 'Change to channel 511' },
      { label: 'News - 521', num: '521', speak: 'Change to channel 521' },
      { label: 'News - 524', num: '524', speak: 'Change to channel 524' },
      { label: 'Movies - 310', num: '310', speak: 'Change to channel 310' },
      { label: 'Tarak Mehta', num: '132', speak: 'Change to channel 132' },
      { label: 'Ramayan', num: '128', speak: 'Change to channel 128' },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    items: [
      { label: 'Play old songs', sub: 'पुराने गाने', speak: 'Play old songs' },
      { label: 'Play comedy videos', sub: 'कॉमेडी वीडियो', speak: 'Play comedy videos' },
      { label: 'Play devotional music', sub: 'भजन', speak: 'Play devotional music' },
      { label: 'Play news clips', sub: 'न्यूज़ वीडियो', speak: 'Play news clips' },
      { label: 'Pause video', sub: 'वीडियो रोकें', speak: 'Pause video' },
      { label: 'Volume down', sub: 'आवाज़ कम', speak: 'Volume down' },
    ],
  },
  {
    id: 'alexa',
    name: 'Alexa',
    items: [
      { label: 'Om chanting', sub: 'ओम चैंटिंग', speak: 'Alexa play Om chanting' },
      { label: 'Hanuman Chalisa', sub: 'हनुमान चालीसा', speak: 'Alexa play Hanuman Chalisa' },
      { label: 'Kishore Kumar songs', sub: 'किशोर कुमार के गाने', speak: 'Alexa play Kishore Kumar songs' },
      { label: 'Bhajan playlist', sub: 'भजन', speak: 'Alexa play bhajan playlist' },
      { label: 'Stop music', sub: 'संगीत बंद', speak: 'Alexa stop music' },
      { label: 'Set volume low', sub: 'आवाज़ कम', speak: 'Alexa set volume low' },
    ],
  },
];
