#!/usr/bin/env python3
"""
Generate Smart Bigrams Database for GazeConnect Pro
====================================================
Builds a comprehensive bigram frequency database from curated English corpus data.
Categories: conversational English, AAC patterns, medical/care, daily needs,
questions, family communication, emotional expression.

Output: python/data/smart_bigrams.json (~2-4 MB)
Format: {"bigrams": {"word1": {"word2": freq, ...}}, "unigrams": {"word": freq}}

Usage:
    python python/scripts/generate_smart_bigrams.py
"""

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# CURATED CORPUS — ~10,000+ sentences covering key AAC communication domains
# Each sentence is weighted by how common that pattern is in real English.
# We repeat high-frequency patterns to simulate real-world distribution.
# ---------------------------------------------------------------------------

# Weight multipliers: sentences in higher-weight categories get repeated
# to simulate their higher real-world frequency
CORPUS_SECTIONS = []

def add_corpus(sentences, weight=1):
    """Add sentences with a frequency weight."""
    for _ in range(weight):
        CORPUS_SECTIONS.extend(sentences)

# ===========================================================================
# 1. CORE CONVERSATIONAL PATTERNS (weight=10 — most common in daily speech)
# ===========================================================================
add_corpus([
    # I want/need patterns
    "I want to go home",
    "I want to eat something",
    "I want to sleep now",
    "I want to watch television",
    "I want to talk to you",
    "I want to see the doctor",
    "I want to drink water",
    "I want to drink tea",
    "I want to drink coffee",
    "I want to drink juice",
    "I want to go outside",
    "I want to go to the bathroom",
    "I want to go to the hospital",
    "I want to go to the market",
    "I want to change position",
    "I want to sit up",
    "I want to lie down",
    "I want to read something",
    "I want to listen to music",
    "I want to call someone",
    "I want some food",
    "I want some water",
    "I want some tea",
    "I want some help",
    "I want my medicine",
    "I want my phone",
    "I want my glasses",
    "I want my pillow",
    "I want my blanket",
    "I need help",
    "I need water",
    "I need food",
    "I need medicine",
    "I need rest",
    "I need to go to the bathroom",
    "I need to see a doctor",
    "I need to sleep",
    "I need to eat",
    "I need to drink",
    "I need my medicine now",
    "I need a pillow",
    "I need a blanket",
    "I need some help please",
    "I need to change position",
    "I need to talk to someone",
    "I need to call my family",

    # I am/feel patterns
    "I am fine",
    "I am okay",
    "I am not feeling well",
    "I am tired",
    "I am hungry",
    "I am thirsty",
    "I am cold",
    "I am hot",
    "I am in pain",
    "I am comfortable",
    "I am uncomfortable",
    "I am happy",
    "I am sad",
    "I am worried",
    "I am scared",
    "I am bored",
    "I am feeling better",
    "I am feeling worse",
    "I am feeling good today",
    "I am feeling sick",
    "I am feeling dizzy",
    "I am feeling weak",
    "I am feeling strong",
    "I am feeling sleepy",
    "I feel good",
    "I feel bad",
    "I feel tired",
    "I feel happy",
    "I feel sad",
    "I feel cold",
    "I feel hot",
    "I feel hungry",
    "I feel thirsty",
    "I feel better now",
    "I feel pain in my back",
    "I feel pain in my leg",
    "I feel pain in my arm",
    "I feel pain in my chest",
    "I feel pain in my head",

    # Can you / Could you patterns
    "Can you help me",
    "Can you come here",
    "Can you get me water",
    "Can you turn on the light",
    "Can you turn off the light",
    "Can you turn on the fan",
    "Can you turn off the fan",
    "Can you open the window",
    "Can you close the window",
    "Can you open the door",
    "Can you close the door",
    "Can you call the doctor",
    "Can you call my family",
    "Can you bring me food",
    "Can you bring me water",
    "Can you bring me my phone",
    "Can you change the channel",
    "Can you help me sit up",
    "Can you help me lie down",
    "Can you please come here",
    "Could you help me please",
    "Could you bring me water",
    "Could you come here please",
    "Could you turn down the volume",
    "Could you turn up the volume",

    # Please patterns
    "Please help me",
    "Please come here",
    "Please get me water",
    "Please bring me food",
    "Please call the doctor",
    "Please call my family",
    "Please turn on the light",
    "Please turn off the light",
    "Please open the window",
    "Please close the door",
    "Please give me my medicine",
    "Please help me change position",
    "Please bring me a blanket",
    "Please bring me a pillow",
    "Please wait a moment",
    "Please tell them I said hello",
    "Please do not worry",
    "Please be careful",
    "Please send a message",
    "Please read this to me",

    # Thank you / Sorry patterns
    "Thank you very much",
    "Thank you for helping me",
    "Thank you for everything",
    "Thank you for being here",
    "Thank you for your help",
    "Thank you for taking care of me",
    "Thank you so much",
    "Thanks for your help",
    "Thanks for everything",
    "Sorry for the trouble",
    "Sorry to bother you",
    "Sorry I cannot do that",

    # Yes/No/Maybe
    "Yes please",
    "Yes I want that",
    "Yes that is right",
    "Yes I am fine",
    "Yes I understand",
    "No thank you",
    "No I do not want that",
    "No that is not right",
    "No I am not okay",
    "Maybe later",
    "Maybe tomorrow",
    "Maybe we can try",
], weight=10)

# ===========================================================================
# 2. QUESTIONS (weight=8 — very common in conversation)
# ===========================================================================
add_corpus([
    # What questions
    "What time is it",
    "What day is it",
    "What is the weather like",
    "What is happening",
    "What is wrong",
    "What do you want",
    "What do you think",
    "What do you mean",
    "What did you say",
    "What did the doctor say",
    "What are you doing",
    "What are we eating today",
    "What is for dinner",
    "What is for lunch",
    "What is on television",
    "What happened",
    "What should I do",
    "What can I do",

    # How questions
    "How are you",
    "How are you doing",
    "How are you feeling",
    "How do you feel",
    "How is the weather",
    "How is everyone",
    "How is your day",
    "How is your health",
    "How was your day",
    "How long will it take",
    "How much does it cost",
    "How much time do we have",
    "How many people are coming",

    # Where questions
    "Where is my phone",
    "Where is my medicine",
    "Where is the remote",
    "Where are you going",
    "Where are my glasses",
    "Where is everyone",
    "Where did you go",
    "Where did you put it",

    # When questions
    "When is the doctor coming",
    "When are you coming back",
    "When is dinner",
    "When is lunch",
    "When will you be back",
    "When did this happen",
    "When can I go home",

    # Who questions
    "Who is there",
    "Who is calling",
    "Who is coming today",
    "Who told you that",
    "Who is at the door",

    # Why questions
    "Why are you late",
    "Why did you do that",
    "Why is this happening",

    # Other question patterns
    "Is everything okay",
    "Is anyone there",
    "Is it time for medicine",
    "Is the doctor here",
    "Are you okay",
    "Are you sure",
    "Are you coming",
    "Are we going",
    "Did you eat",
    "Did you sleep well",
    "Did you call the doctor",
    "Do you understand",
    "Do you need anything",
    "Do you have time",
    "Do you know what happened",
    "Have you eaten",
    "Have you seen my phone",
    "Will you help me",
    "Will you come back",
    "Will you be here tomorrow",
], weight=8)

# ===========================================================================
# 3. FAMILY & SOCIAL (weight=7)
# ===========================================================================
add_corpus([
    "I love you",
    "I love you all",
    "I miss you",
    "I miss everyone",
    "I am proud of you",
    "I am thinking of you",
    "Take care of yourself",
    "Take care of your health",
    "Be careful on the road",
    "Come home safely",
    "Give me a hug",
    "Tell the children I love them",
    "Tell mother I said hello",
    "Tell father I miss him",
    "How are the children",
    "How is the family",
    "How is mother doing",
    "How is father doing",
    "Call me when you get there",
    "Let me know when you arrive",
    "I want to see the children",
    "I want to talk to the family",
    "Bring the children to visit",
    "When are they coming to visit",
    "I hope you are well",
    "I hope everyone is healthy",
    "God bless you",
    "God bless the family",
    "Good morning everyone",
    "Good night everyone",
    "Sleep well",
    "Have a good day",
    "Happy birthday",
    "Happy anniversary",
    "Congratulations",
    "I am sorry for what happened",
    "Do not worry about me",
    "Everything will be okay",
    "We will get through this together",
    "You are doing a great job",
    "I appreciate your help",
    "I am grateful for your support",
], weight=7)

# ===========================================================================
# 4. MEDICAL & CARE (weight=6)
# ===========================================================================
add_corpus([
    "I need my medication",
    "I need pain medicine",
    "It is time for my medicine",
    "The pain is getting worse",
    "The pain is getting better",
    "I have a headache",
    "I have a stomach ache",
    "I have difficulty breathing",
    "I cannot breathe properly",
    "I cannot swallow well",
    "My throat is dry",
    "My mouth is dry",
    "My eyes are dry",
    "My back hurts",
    "My neck hurts",
    "My legs hurt",
    "My arms hurt",
    "I feel nauseous",
    "I feel dizzy",
    "I feel weak",
    "I cannot move my legs",
    "I cannot move my arms",
    "I need to see the doctor",
    "When is my next appointment",
    "What did the doctor say",
    "I need physical therapy",
    "I need to do my exercises",
    "Help me with my exercises",
    "I need the suction machine",
    "I need the breathing machine",
    "Check my blood pressure",
    "Check my temperature",
    "Check my oxygen level",
    "I am having trouble sleeping",
    "I need a sleeping pill",
    "I need something for the pain",
    "The medicine is making me dizzy",
    "The medicine is making me sleepy",
    "I have an allergic reaction",
    "Call the nurse",
    "Call the ambulance",
    "This is an emergency",
    "I need to go to the hospital",
    "I have an appointment today",
    "I have an appointment tomorrow",
], weight=6)

# ===========================================================================
# 5. DAILY NEEDS & COMFORT (weight=8)
# ===========================================================================
add_corpus([
    # Food and drink
    "I want to eat breakfast",
    "I want to eat lunch",
    "I want to eat dinner",
    "I want some soup",
    "I want some rice",
    "I want some bread",
    "I want some fruit",
    "I want something sweet",
    "I want something to drink",
    "I want hot water",
    "I want cold water",
    "I am not hungry right now",
    "I just want something light",
    "What is for breakfast today",
    "What is for lunch today",
    "What is for dinner today",

    # Comfort
    "I am too hot",
    "I am too cold",
    "Turn on the air conditioning",
    "Turn off the air conditioning",
    "Turn on the heater",
    "Turn off the heater",
    "Open the window please",
    "Close the window please",
    "I need another blanket",
    "This pillow is uncomfortable",
    "Can you adjust my bed",
    "Can you adjust my pillow",
    "Can you adjust my chair",
    "I want to sit in the wheelchair",
    "I want to go back to bed",
    "Help me get up",
    "Help me sit down",
    "Help me turn over",
    "I need to stretch",
    "My position is uncomfortable",

    # Environment
    "It is too bright",
    "It is too dark",
    "It is too loud",
    "It is too quiet",
    "The room is too hot",
    "The room is too cold",
    "Turn on the television",
    "Turn off the television",
    "Change the channel",
    "Turn up the volume",
    "Turn down the volume",
    "Play some music",
    "Stop the music",
    "What show is on",

    # Hygiene
    "I need to brush my teeth",
    "I need to wash my face",
    "I need to take a bath",
    "I need to use the bathroom",
    "I need a clean shirt",
    "I need clean clothes",
    "Can you comb my hair",
    "I need a tissue",
    "I need a towel",
], weight=8)

# ===========================================================================
# 6. GENERAL ENGLISH PATTERNS (weight=5 — broad coverage)
# ===========================================================================
add_corpus([
    # Common sentence starters
    "I think we should",
    "I think it is",
    "I think that is",
    "I think you are right",
    "I think you should",
    "I believe that",
    "I believe we can",
    "I remember when",
    "I remember that",
    "I hope so",
    "I hope not",
    "I hope you",
    "I hope we",
    "I hope they",
    "I know that",
    "I know how",
    "I know what",
    "I know you",
    "I know we",
    "I told you",
    "I told them",
    "I asked them",
    "I asked her",
    "I asked him",
    "I was thinking about",
    "I was going to",
    "I was trying to",
    "I was looking for",
    "I used to",
    "I have been",
    "I have never",
    "I have always",
    "I will be",
    "I will try",
    "I will do",
    "I would like to",
    "I would like some",
    "I should have",
    "I could have",
    "I might have",

    # You patterns
    "You are right",
    "You are wrong",
    "You are welcome",
    "You are very kind",
    "You are the best",
    "You should go",
    "You should eat",
    "You should rest",
    "You should not worry",
    "You can do it",
    "You can go now",
    "You do not have to",
    "You need to",
    "You need to rest",
    "You need to eat",

    # We patterns
    "We should go",
    "We should eat",
    "We should talk",
    "We should wait",
    "We can do this",
    "We can try",
    "We will see",
    "We will be fine",
    "We need to",
    "We need to talk",
    "We have to",
    "We used to",

    # They/He/She patterns
    "They are coming",
    "They are here",
    "They will be here soon",
    "They said they would",
    "They told me that",
    "He is coming",
    "He is here",
    "He said that",
    "He will be back",
    "He told me",
    "She is coming",
    "She is here",
    "She said that",
    "She will be back",
    "She told me",

    # It/This/That patterns
    "It is okay",
    "It is fine",
    "It is good",
    "It is bad",
    "It is time to go",
    "It is time for dinner",
    "It is time for bed",
    "It is very important",
    "It was a good day",
    "It will be fine",
    "It will get better",
    "It does not matter",
    "It makes me happy",
    "It makes me sad",
    "This is good",
    "This is bad",
    "This is important",
    "This is not right",
    "This is what I want",
    "That is right",
    "That is wrong",
    "That is not true",
    "That is a good idea",
    "That sounds good",
    "That would be nice",

    # There is/are
    "There is something wrong",
    "There is someone at the door",
    "There is food in the kitchen",
    "There are many things to do",
    "There are people waiting",

    # Common verbs with objects
    "Let me know",
    "Let me think",
    "Let me see",
    "Let us go",
    "Let us try",
    "Let us wait",
    "Make sure you",
    "Make sure to",
    "Make it stop",
    "Give me a minute",
    "Give me some time",
    "Give me the phone",
    "Take your time",
    "Take care",
    "Take me there",
    "Tell me about it",
    "Tell me what happened",
    "Tell me the truth",
    "Show me how",
    "Show me what",
    "Keep going",
    "Keep trying",
    "Keep it safe",
    "Put it there",
    "Put it down",
    "Put it away",
    "Get me some water",
    "Get me my phone",
    "Get ready",
    "Come here please",
    "Come back soon",
    "Come with me",
    "Go ahead",
    "Go away",
    "Go to sleep",
    "Go and eat",
    "Wait for me",
    "Wait a moment",
    "Wait a minute",
    "Look at this",
    "Look at that",
    "Look at me",
    "Listen to me",
    "Listen to this",
    "Help me please",
    "Help me with this",
    "Stop doing that",
    "Stop it please",
    "Start the car",
    "Start again",
    "Try again",
    "Try this one",
    "Send a message",
    "Send it now",
    "Read this to me",
    "Read the message",
    "Write this down",
    "Check the phone",
    "Check the door",
    "Close the door",
    "Open the window",
    "Find my phone",
    "Find the remote",
    "Bring me the newspaper",
    "Bring me some food",
], weight=5)

# ===========================================================================
# 7. TIME & SCHEDULING (weight=4)
# ===========================================================================
add_corpus([
    "What time is it now",
    "It is getting late",
    "It is still early",
    "We are running late",
    "We have plenty of time",
    "I will be there in a minute",
    "I will be there soon",
    "See you tomorrow",
    "See you later",
    "See you soon",
    "See you next week",
    "Maybe next time",
    "Maybe another day",
    "Not right now",
    "Not today",
    "Not yet",
    "In a little while",
    "In a few minutes",
    "After lunch",
    "After dinner",
    "Before bed",
    "Before lunch",
    "This morning",
    "This afternoon",
    "This evening",
    "Tonight",
    "Last night",
    "Last week",
    "Last month",
    "Next week",
    "Next month",
    "Next year",
    "Every day",
    "Every morning",
    "Every night",
    "Every week",
    "All day long",
    "All night long",
    "The whole day",
    "The whole week",
    "Right now",
    "Right away",
    "As soon as possible",
], weight=4)

# ===========================================================================
# 8. EMOTIONS & FEELINGS (weight=5)
# ===========================================================================
add_corpus([
    "I am feeling lonely",
    "I am feeling anxious",
    "I am feeling depressed",
    "I am feeling frustrated",
    "I am feeling grateful",
    "I am feeling hopeful",
    "I am feeling proud",
    "I am feeling confused",
    "I am feeling overwhelmed",
    "I am feeling peaceful",
    "I am feeling nervous",
    "I am feeling excited",
    "I am feeling relieved",
    "I am not happy about this",
    "I am not comfortable with this",
    "It makes me feel better",
    "It makes me feel worse",
    "It makes me feel happy",
    "It makes me feel sad",
    "I do not like this",
    "I do not want to talk about it",
    "I do not feel safe",
    "I am worried about the future",
    "I am scared of falling",
    "I miss the way things were",
    "I wish I could do more",
    "I wish things were different",
    "I am doing my best",
    "I am trying my best",
    "I will not give up",
    "I am stronger than this",
    "Every day is a new day",
    "Things will get better",
    "I have so much to be thankful for",
    "You make me feel better",
    "You make me happy",
    "Your visit means a lot",
    "Your support means everything",
], weight=5)

# ===========================================================================
# 9. GENERAL HIGH-FREQUENCY BIGRAMS (weight=3)
# These sentences are designed to boost common English word pairs
# ===========================================================================
add_corpus([
    # "the" followed by common words
    "the best way to do this",
    "the first thing we need",
    "the last time we talked",
    "the next step is to",
    "the same thing happened before",
    "the other day I was thinking",
    "the whole family is here",
    "the most important thing is",
    "the only way to know",
    "the right thing to do",
    "the new one is better",
    "the old one was good",
    "the big question is",
    "the small things matter",
    "the good news is",
    "the bad news is",
    "the problem is that",
    "the answer is yes",
    "the truth is that",
    "the reason why is",
    "the fact that we",
    "the way you said it",
    "the place where we",
    "the people who came",
    "the man who helped",
    "the woman who called",
    "the children are playing",
    "the doctor will come",
    "the medicine is working",
    "the weather is nice today",
    "the water is too cold",
    "the food is ready",
    "the door is open",
    "the window is closed",
    "the light is on",

    # "to" followed by common words
    "to the store and back",
    "to be honest with you",
    "to be fair about it",
    "to be able to do",
    "to get the best result",
    "to go back home now",
    "to do the right thing",
    "to make sure everything",
    "to see what happens",
    "to know the truth",
    "to help you with that",
    "to have a good time",
    "to take care of it",
    "to find out what happened",
    "to give you some advice",
    "to tell you the truth",
    "to keep it simple",
    "to put it simply",
    "to try something new",
    "to start all over",

    # "a" followed by common words
    "a good idea for everyone",
    "a bad feeling about this",
    "a new day has begun",
    "a long time ago we",
    "a little bit more please",
    "a lot of people think",
    "a few minutes ago they",
    "a great deal of work",
    "a big change is coming",
    "a small step forward",
    "a nice day outside today",

    # Common verb chains
    "going to be a long day",
    "going to have to wait",
    "going to try my best",
    "going to make it work",
    "going to see what happens",
    "trying to understand what you",
    "trying to find the right",
    "trying to get some rest",
    "trying to be patient here",
    "want to know more about",
    "want to make sure that",
    "want to thank you for",
    "need to find a way",
    "need to think about it",
    "need to take a break",
    "have to go now but",
    "have to wait and see",
    "have to be careful with",
    "used to be so much",
    "used to live in the",

    # "with" patterns
    "with the family today",
    "with you all the time",
    "with my friend at the",
    "with the help of everyone",
    "with all my heart I",

    # "for" patterns
    "for a long time now",
    "for the first time ever",
    "for everyone in the family",
    "for your help and support",
    "for the best possible outcome",

    # "in" patterns
    "in the morning I usually",
    "in the afternoon we can",
    "in the evening I like",
    "in the kitchen there is",
    "in the room next to",
    "in a few days we",
    "in my opinion the best",

    # "on" patterns
    "on the table over there",
    "on the way home now",
    "on my mind all day",
    "on the other hand we",
    "on the phone right now",

    # "at" patterns
    "at the hospital for a",
    "at home right now and",
    "at the door someone is",
    "at night I cannot sleep",
    "at the same time we",

    # Misc high-freq pairs
    "more than enough for everyone",
    "less than what we expected",
    "better than before by far",
    "worse than yesterday but still",
    "just like the old times",
    "even though it was hard",
    "so that we can move",
    "as well as the others",
    "not only that but also",
    "both of them are here",
    "each other very much indeed",
    "one of the best things",
    "some of the people here",
    "all of the children are",
    "most of the time I",
    "part of the reason is",
    "kind of like what you",
    "sort of the same thing",
    "out of the question now",
    "because of what happened today",
    "instead of waiting for them",
    "in front of the house",
    "next to the window there",
    "close to the hospital is",
    "far from home but safe",
    "on top of everything else",
    "in spite of all that",
    "as soon as you can",
    "as long as we try",
    "as much as I want",
    "no matter what happens we",
    "every time I think about",
    "the more you practice the",
    "so far so good and",
    "right now I just want",
    "by the way did you",
    "of course I will help",
    "in fact I think you",
    "at least we still have",
    "at most it will take",
    "for example you could try",
    "such as food and water",
    "as if nothing happened at",
], weight=3)

# ===========================================================================
# 10. ADDITIONAL HIGH-FREQUENCY ENGLISH PAIRS (weight=2)
# Designed purely to boost common word-pair statistics
# ===========================================================================
add_corpus([
    "able to do the work",
    "about the situation at home",
    "after the meeting we should",
    "again and again they tried",
    "already have enough to eat",
    "always remember to take your",
    "another chance to make it",
    "around the house looking for",
    "ask them to come over",
    "away from the noise and",
    "back to the beginning again",
    "before the end of today",
    "between you and me the",
    "both are doing well today",
    "bring it here right now",
    "but I do not think",
    "call me back when you",
    "change the way we think",
    "could not have done it",
    "day after day we wait",
    "different from what I expected",
    "does not make any sense",
    "down the road from here",
    "during the night I woke",
    "early in the morning she",
    "enough is enough now stop",
    "even more important than before",
    "every single day I try",
    "everything is going to be",
    "family is the most important",
    "feel like giving up but",
    "finally got the chance to",
    "first of all thank you",
    "from now on I will",
    "getting better every single day",
    "give them a chance to",
    "glad to hear that you",
    "good to see you again",
    "had to make a decision",
    "hard to believe that it",
    "has been a long day",
    "here is what I think",
    "hope to see you soon",
    "how about we try something",
    "if you need anything call",
    "important to take care of",
    "into the room and sat",
    "just a little bit more",
    "keep me posted on the",
    "last time we spoke about",
    "left the house early today",
    "like I said before the",
    "little by little things improve",
    "long story short the answer",
    "look forward to seeing you",
    "made a big difference in",
    "many people have the same",
    "might as well try it",
    "more or less the same",
    "much better than expected today",
    "must have been very hard",
    "never give up on your",
    "nice to meet you here",
    "nothing to worry about at",
    "now is the time to",
    "often think about the good",
    "once upon a time there",
    "only if you really want",
    "other than that everything is",
    "over and over again they",
    "people are very kind here",
    "probably the best thing to",
    "put your mind at ease",
    "quite a while since we",
    "ready to go whenever you",
    "really appreciate your help with",
    "right here waiting for you",
    "said that he would come",
    "same as before nothing changed",
    "should be done by tomorrow",
    "since the beginning of the",
    "something is wrong with the",
    "sometimes I just want to",
    "still the same as before",
    "sure about what to do",
    "talk to each other more",
    "than what we thought it",
    "their own way of doing",
    "then we can decide what",
    "things are looking up now",
    "through the window I can",
    "together we are stronger than",
    "told me that everything was",
    "too much to handle right",
    "under the circumstances I think",
    "understand how you feel about",
    "until we meet again take",
    "upon further thought I believe",
    "very grateful for all your",
    "want to spend more time",
    "well done you did great",
    "when you get a chance",
    "which one do you prefer",
    "while waiting for the doctor",
    "whole thing makes me think",
    "will always be here for",
    "without a doubt the best",
    "work together as a team",
    "would have been nice if",
    "wrong about what I said",
    "years ago things were different",
    "your health is the most",
], weight=2)

# ===========================================================================
# 11. SHORT COMMON PHRASES (weight=6 — high frequency, short)
# ===========================================================================
add_corpus([
    "I am",
    "I was",
    "I will",
    "I have",
    "I had",
    "I can",
    "I could",
    "I would",
    "I should",
    "I do",
    "I did",
    "I want",
    "I need",
    "I like",
    "I love",
    "I feel",
    "I know",
    "I think",
    "I hope",
    "I wish",
    "I see",
    "I hear",
    "I said",
    "I told",
    "I ask",
    "I try",
    "I go",
    "you are",
    "you were",
    "you will",
    "you have",
    "you can",
    "you could",
    "you should",
    "you would",
    "you want",
    "you need",
    "you know",
    "you think",
    "he is",
    "he was",
    "he will",
    "he has",
    "he can",
    "he said",
    "she is",
    "she was",
    "she will",
    "she has",
    "she can",
    "she said",
    "it is",
    "it was",
    "it will",
    "it has",
    "it can",
    "we are",
    "we were",
    "we will",
    "we have",
    "we can",
    "we should",
    "we need",
    "they are",
    "they were",
    "they will",
    "they have",
    "they can",
    "they said",
    "there is",
    "there are",
    "there was",
    "there were",
    "this is",
    "this was",
    "that is",
    "that was",
    "what is",
    "what was",
    "what will",
    "what can",
    "what do",
    "what did",
    "what are",
    "how is",
    "how was",
    "how are",
    "how do",
    "how did",
    "how can",
    "where is",
    "where are",
    "where did",
    "when is",
    "when did",
    "when will",
    "when can",
    "who is",
    "who was",
    "who will",
    "who can",
    "why is",
    "why did",
    "why do",
    "do not",
    "did not",
    "can not",
    "will not",
    "would not",
    "should not",
    "could not",
    "have not",
    "has not",
    "was not",
    "were not",
    "is not",
    "are not",
    "not sure",
    "not yet",
    "not now",
    "not today",
    "not here",
    "not there",
    "not good",
    "not bad",
    "not right",
    "not wrong",
    "not enough",
    "too much",
    "too many",
    "too late",
    "too early",
    "too hot",
    "too cold",
    "too tired",
    "very good",
    "very well",
    "very much",
    "very nice",
    "very kind",
    "very happy",
    "very sad",
    "very tired",
    "very important",
    "so much",
    "so many",
    "so good",
    "so far",
    "so long",
    "as well",
    "as much",
    "as soon",
    "as long",
    "of course",
    "at least",
    "at all",
    "at home",
    "at work",
    "in fact",
    "in time",
    "on time",
    "right now",
    "right here",
    "right away",
    "come here",
    "come back",
    "go home",
    "go back",
    "go away",
    "get up",
    "get out",
    "get back",
    "sit down",
    "lie down",
    "stand up",
    "turn on",
    "turn off",
    "pick up",
    "put down",
    "look at",
    "look for",
    "wait for",
    "ask for",
    "care for",
    "thank you",
    "good morning",
    "good afternoon",
    "good evening",
    "good night",
    "see you",
    "take care",
    "be careful",
    "no problem",
    "no worries",
    "of course",
    "all right",
    "for sure",
    "you too",
    "me too",
], weight=6)


# ===========================================================================
# BUILD THE BIGRAM DATABASE
# ===========================================================================

def tokenize(text):
    """Extract words (3+ chars or common short words)."""
    words = re.findall(r'[a-zA-Z]+', text.lower())
    return [w for w in words if len(w) >= 3 or w in ('i', 'a')]

def build_bigram_database():
    """Process corpus and build frequency-scored bigram database."""
    bigrams = defaultdict(lambda: defaultdict(int))
    unigrams = defaultdict(int)

    print(f"Processing {len(CORPUS_SECTIONS)} weighted sentences...")

    for sentence in CORPUS_SECTIONS:
        words = tokenize(sentence)
        for i, word in enumerate(words):
            unigrams[word] += 1
            if i > 0:
                prev = words[i - 1]
                bigrams[prev][word] += 1

    # Prune: keep only pairs with count >= 2 (removes noise)
    pruned_bigrams = {}
    total_pairs = 0
    for w1 in bigrams:
        followers = {w2: count for w2, count in bigrams[w1].items() if count >= 2}
        if followers:
            # Sort by frequency, keep top 30 followers per word
            top_followers = dict(sorted(followers.items(), key=lambda x: -x[1])[:30])
            pruned_bigrams[w1] = top_followers
            total_pairs += len(top_followers)

    # Prune unigrams: keep only words with count >= 2
    pruned_unigrams = {w: c for w, c in unigrams.items() if c >= 2}

    print(f"Built {total_pairs} unique bigram pairs from {len(pruned_bigrams)} context words")
    print(f"Unigrams: {len(pruned_unigrams)} words")

    return pruned_bigrams, pruned_unigrams


def main():
    bigrams, unigrams = build_bigram_database()

    output = {
        "version": 1,
        "description": "Smart bigram frequencies for GazeConnect Pro word prediction",
        "bigrams": bigrams,
        "unigrams": unigrams,
    }

    # Write to python/data/smart_bigrams.json
    output_path = Path(__file__).parent.parent / "data" / "smart_bigrams.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=1)

    size_kb = output_path.stat().st_size / 1024
    print(f"\nWritten to: {output_path}")
    print(f"File size: {size_kb:.1f} KB")
    print(f"Bigram context words: {len(bigrams)}")
    print(f"Total bigram pairs: {sum(len(v) for v in bigrams.values())}")
    print(f"Unigram vocabulary: {len(unigrams)}")

    # Show some example predictions
    print("\n--- Example predictions ---")
    examples = ["i want", "how are", "please", "the", "can you", "i need", "thank"]
    for phrase in examples:
        words = tokenize(phrase)
        if words:
            last = words[-1]
            if last in bigrams:
                top5 = sorted(bigrams[last].items(), key=lambda x: -x[1])[:5]
                preds = ", ".join(f"{w}({c})" for w, c in top5)
                print(f'  "{phrase} ..." -> {preds}')
            else:
                print(f'  "{phrase} ..." -> (no bigrams for "{last}")')


if __name__ == '__main__':
    main()
